use super::*;
use std::collections::{BTreeMap, BTreeSet};

fn type_name(schema: &Value) -> String {
    if let Some(title) = schema["title"].as_str() {
        title.replace(|c: char| !c.is_ascii_alphanumeric() && c != '_', "_")
    } else {
        typescript(schema)
    }
}
fn collect(schema: &Value, types: &mut BTreeMap<String, Value>) {
    if let Some(defs) = schema["$defs"].as_object() {
        for (name, def) in defs {
            types.insert(name.clone(), def.clone());
        }
    }
    if schema["title"].is_string()
        && !matches!(
            type_name(schema).as_str(),
            "string" | "number" | "boolean" | "null" | "Json" | "never"
        )
    {
        types.insert(type_name(schema), schema.clone());
    }
}
fn typescript(v: &Value) -> String {
    if v == &Value::Bool(true) || v.as_object().is_some_and(|o| o.is_empty()) {
        return "Json".into();
    }
    if v == &Value::Bool(false) {
        return "never".into();
    }
    if let Some(r) = v["$ref"].as_str() {
        return r.rsplit('/').next().unwrap().into();
    }
    if let Some(c) = v.get("const") {
        return c.to_string();
    }
    if let Some(values) = v["enum"].as_array() {
        return values
            .iter()
            .map(Value::to_string)
            .collect::<Vec<_>>()
            .join(" | ");
    }
    for (key, join) in [("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")] {
        if let Some(values) = v[key].as_array() {
            return format!(
                "({})",
                values.iter().map(typescript).collect::<Vec<_>>().join(join)
            );
        }
    }
    if let Some(types) = v["type"].as_array() {
        return types
            .iter()
            .map(|t| {
                let mut x = v.clone();
                x["type"] = t.clone();
                typescript(&x)
            })
            .collect::<Vec<_>>()
            .join(" | ");
    }
    match v["type"].as_str() {
        Some("string") => "string".into(),
        Some("number" | "integer") => "number".into(),
        Some("boolean") => "boolean".into(),
        Some("null") => "null".into(),
        Some("array") => format!("Array<{}>", typescript(&v["items"])),
        Some("object") => {
            let required: BTreeSet<&str> = v["required"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect();
            let mut fields = vec![];
            if let Some(properties) = v["properties"].as_object() {
                for (name, schema) in properties {
                    fields.push(format!(
                        "{}{}: {}",
                        json!(name),
                        if required.contains(name.as_str()) {
                            ""
                        } else {
                            "?"
                        },
                        typescript(schema)
                    ));
                }
            }
            if fields.is_empty() {
                return format!(
                    "{{ [key: string]: {} }}",
                    if v["additionalProperties"].is_object() {
                        typescript(&v["additionalProperties"])
                    } else {
                        "Json".into()
                    }
                );
            }
            format!("{{ {} }}", fields.join("; "))
        }
        _ => "Json".into(),
    }
}
pub fn declarations() -> String {
    declarations_for(methods())
}
pub fn sites_declarations() -> String {
    declarations_for(sites_methods())
        .replace("AgentPlatform", "AgentSitesContext")
        .replace("interface Platform", "interface SitesContext")
        .replace("Omit<Platform,", "Omit<SitesContext,")
        .replace("Platform[", "SitesContext[")
}
fn declarations_for(methods: Vec<Method>) -> String {
    let mut types = BTreeMap::new();
    for m in &methods {
        for p in &m.parameters {
            collect(&p.schema, &mut types);
        }
        collect(&m.result, &mut types);
    }
    let mut out = String::from(
        "// Generated by platform-javascript-sdk. Do not edit.\nexport type Json = null | boolean | number | string | Json[] | { [key: string]: Json };\n",
    );
    for (name, schema) in types {
        out.push_str(&format!("export type {name} = {};\n", typescript(&schema)));
    }
    out.push_str("\nexport interface Platform {\n");
    let mut groups: BTreeMap<&str, Vec<&Method>> = BTreeMap::new();
    for m in &methods {
        groups
            .entry(m.name.split('.').next().unwrap())
            .or_default()
            .push(m);
    }
    for (group, methods) in groups {
        out.push_str(&format!("  readonly {group}: Readonly<{{\n"));
        for m in methods {
            out.push_str(&format!(
                "    /** {} */\n    {}({}): Promise<{}>;\n",
                m.description,
                m.name.split('.').nth(1).unwrap(),
                m.parameters
                    .iter()
                    .map(|p| format!(
                        "{}{}: {}",
                        p.name,
                        if p.optional && !m.mutation { "?" } else { "" },
                        type_name(&p.schema)
                    ))
                    .collect::<Vec<_>>()
                    .join(", "),
                type_name(&m.result)
            ));
        }
        out.push_str("  }>;\n");
    }
    out.push_str("}\n");
    let mut mutable: BTreeMap<&str, Vec<&Method>> = BTreeMap::new();
    for m in &methods {
        if m.mutation {
            mutable
                .entry(m.name.split('.').next().unwrap())
                .or_default()
                .push(m);
        }
    }
    out.push_str(&format!("\n/** Agent cells may omit keys; the trusted adapter assigns and journals them. */\nexport interface AgentPlatform extends Omit<Platform, {}> {{\n",mutable.keys().map(|k|format!("'{k}'")).collect::<Vec<_>>().join(" | ")));
    for (group, methods) in mutable {
        out.push_str(&format!(
            "  readonly {group}: Omit<Platform['{group}'], {}> & Readonly<{{\n",
            methods
                .iter()
                .map(|m| format!("'{}'", m.name.split('.').nth(1).unwrap()))
                .collect::<Vec<_>>()
                .join(" | ")
        ));
        for m in methods {
            out.push_str(&format!(
                "    {}({}): Promise<{}>;\n",
                m.name.split('.').nth(1).unwrap(),
                m.parameters
                    .iter()
                    .map(|p| format!(
                        "{}{}: {}",
                        p.name,
                        if p.optional { "?" } else { "" },
                        type_name(&p.schema)
                    ))
                    .collect::<Vec<_>>()
                    .join(", "),
                type_name(&m.result)
            ));
        }
        out.push_str("  }>;\n");
    }
    out.push_str("}\n");
    out
}
pub fn documentation() -> String {
    let mut out = String::from(
        "# Platform JavaScript SDK\n\nGenerated from the shared Rust capability contracts. Platform methods are shared by code-mode cells and site handlers. Sites methods are agent-only and require a session-bound Sites harness.\n\nMutations in site handlers require a stable `options.idempotencyKey`. Agent code mode assigns one before dispatch if omitted. Explicit keys are preserved. A mutation replay returns its acceptance receipt; getters return current state.\n\n",
    );
    for m in methods().into_iter().chain(sites_methods()) {
        out.push_str(&format!(
            "## ctx.{}\n\n{}\n\n```ts\n{}({}): Promise<{}>\n```\n\n{}\n\n",
            if m.name.starts_with("sites.") {
                m.name.to_owned()
            } else {
                format!("platform.{}", m.name)
            },
            m.description,
            m.name,
            m.parameters
                .iter()
                .map(|p| format!(
                    "{}{}: {}",
                    p.name,
                    if p.optional { "?" } else { "" },
                    type_name(&p.schema)
                ))
                .collect::<Vec<_>>()
                .join(", "),
            type_name(&m.result),
            if m.mutation {
                "Mutation: preserve its operation identity across retries."
            } else {
                "Read: scoped by the trusted caller transport."
            }
        ));
    }
    out
}
