// Generated by platform-javascript-sdk. Do not edit.
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type AnyValue = Json;
export type Files = { "backend": string; "frontend": string };
export type MutationOptions = { "idempotencyKey": string };
export type Patch = { "patch": string };
export type Request = { "body"?: Json; "method": string; "path": string; "query"?: { [key: string]: string } };
export type Source = { "files": Files; "releaseId": string | null; "siteId": string };
export type Sql = { "params"?: Array<Json>; "sql": string };
export type Uuid = string;

export interface SitesContext {
  readonly sites: Readonly<{
    /** Get temporary content access for the live frontend. Backend calls still require the authenticated dashboard viewer bridge. */
    preview(): Promise<AnyValue>;
    /** Read the bound site's live index.html and backend.js. No workspace or version argument is needed. */
    read(): Promise<Source>;
    /** Apply ordinary patch text to index.html and/or backend.js and make the pair live. Check the returned status; conflict means read and patch again with a new operation key. */
    applyPatch(input: Patch, options: MutationOptions): Promise<AnyValue>;
    /** Inspect a saved edit operation without applying it again. */
    operation(operationId: Uuid): Promise<AnyValue>;
    /** Invoke the live backend. Writes and Platform calls are real effects; inspect interrupted invocations before repeating them. */
    invoke(input: Request, options: MutationOptions): Promise<AnyValue>;
    /** Inspect one backend invocation, including its logs. */
    invocation(invocationId: Uuid): Promise<AnyValue>;
    /** Read recent bounded backend invocation summaries. */
    logs(): Promise<AnyValue>;
    /** Run bounded read-only SQL against the live site database. Use LIMIT and explicit columns. */
    query(input: Sql): Promise<AnyValue>;
    /** Run one SQL data or schema statement on the live database. The write and its receipt commit together. Code snapshots do not undo database changes. */
    execute(input: Sql, options: MutationOptions): Promise<AnyValue>;
  }>;
}

/** Agent cells may omit keys; the trusted adapter assigns and journals them. */
export interface AgentSitesContext extends Omit<SitesContext, 'sites'> {
  readonly sites: Omit<SitesContext['sites'], 'applyPatch' | 'invoke' | 'execute'> & Readonly<{
    applyPatch(input: Patch, options?: MutationOptions): Promise<AnyValue>;
    invoke(input: Request, options?: MutationOptions): Promise<AnyValue>;
    execute(input: Sql, options?: MutationOptions): Promise<AnyValue>;
  }>;
}
