// @generated from the curated OpenRouter catalog. Add models only after review.

/// Complete allowlist of models accepted by this provider.
pub const OPENROUTER_MODELS: &[OpenRouterModel] = &[
    OpenRouterModel {
        id: "google/gemini-3.7-flash",
        name: "Google: Gemini 3.7 Flash",
        canonical_slug: "google/gemini-3.7-flash-20260813",
        pricing: ModelPricing {
            base: ModelCost {
                input: 0.375,
                output: 1.875,
                cache_read: 0.0375,
                cache_write: 0.020_833_333_333_333_3,
            },
            above: None,
        },
        context_window: 1_048_576,
        max_tokens: 65_536,
        supported_parameters: &[
            "include_reasoning",
            "max_tokens",
            "reasoning",
            "reasoning_effort",
            "response_format",
            "seed",
            "stop",
            "structured_outputs",
            "temperature",
            "tool_choice",
            "tools",
            "top_p",
        ],
    },
    OpenRouterModel {
        id: "meta/muse-spark-1.2-contributor",
        name: "Meta: Muse Spark 1.2 Contributor",
        canonical_slug: "meta/muse-spark-1.2-contributor-20260805",
        pricing: ModelPricing {
            base: ModelCost {
                input: 0.10,
                output: 0.20,
                cache_read: 0.002,
                cache_write: 0.0,
            },
            above: None,
        },
        context_window: 1_048_576,
        // OpenRouter does not currently publish a separate completion limit.
        max_tokens: 1_048_576,
        supported_parameters: &[
            "include_reasoning",
            "max_tokens",
            "reasoning",
            "repetition_penalty",
            "response_format",
            "structured_outputs",
            "temperature",
            "tool_choice",
            "tools",
            "top_k",
            "top_p",
        ],
    },
    OpenRouterModel {
        id: "deepseek/deepseek-v4-flash-vision-exp",
        name: "DeepSeek: DeepSeek V4 Flash Vision Exp",
        canonical_slug: "deepseek/deepseek-v4-flash-vision-exp-20260821",
        pricing: ModelPricing {
            base: ModelCost {
                input: 0.22,
                output: 0.66,
                cache_read: 0.007,
                cache_write: 0.0,
            },
            above: None,
        },
        context_window: 1_048_576,
        max_tokens: 384_000,
        supported_parameters: &[
            "frequency_penalty",
            "include_reasoning",
            "logprobs",
            "max_tokens",
            "presence_penalty",
            "reasoning",
            "reasoning_effort",
            "response_format",
            "stop",
            "temperature",
            "tool_choice",
            "tools",
            "top_logprobs",
            "top_p",
        ],
    },
    OpenRouterModel {
        id: "z-ai/glm-5.3",
        name: "Z.ai: GLM 5.3",
        canonical_slug: "z-ai/glm-5.3-20260816",
        pricing: ModelPricing {
            base: ModelCost {
                input: 1.40,
                output: 4.40,
                cache_read: 0.26,
                cache_write: 0.0,
            },
            above: None,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
        supported_parameters: &[
            "include_reasoning",
            "max_tokens",
            "reasoning",
            "reasoning_effort",
            "response_format",
            "temperature",
            "tool_choice",
            "tools",
            "top_k",
            "top_p",
        ],
    },
    OpenRouterModel {
        id: "stealth/ox-alpha",
        name: "Ox Alpha",
        canonical_slug: "stealth/ox-alpha",
        pricing: ModelPricing {
            base: ModelCost {
                input: 0.0,
                output: 0.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            above: None,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
        supported_parameters: &[
            "include_reasoning",
            "max_tokens",
            "reasoning",
            "reasoning_effort",
            "response_format",
            "temperature",
            "tool_choice",
            "tools",
            "top_k",
            "top_p",
        ],
    },
];
