/** Backend SDK v1. Bundle dependencies into backend.js; no Node/browser host APIs. */
export type SqlValue = null | string | number;
export type Row = Record<string, SqlValue>;
export interface Statement { sql: string; params?: SqlValue[] }
export interface WriteResult { changes: number; rows: Row[] }
export interface Transaction {
  query(sql: string, params?: SqlValue[]): Promise<Row[]>;
  /** Data writes only (INSERT/UPDATE/DELETE). Create/alter schema with the agent authoring SDK before activating a handler. */
  execute(sql: string, params?: SqlValue[]): Promise<WriteResult>;
}
export interface Database extends Transaction {
  batch(statements: Statement[]): Promise<WriteResult[]>;
  transaction<T>(fn: (tx: Transaction) => Promise<T>): Promise<T>;
}
/** Completion callback POST body. Application callback payload is nested in payload. */
export interface CompletionEvent {
  id: string;
  type: 'run.completed' | 'run.failed' | 'run.aborted';
  subscriptionId: string;
  sessionId: string;
  runId: string;
  status: 'completed' | 'failed' | 'aborted';
  finishedAt: string;
  payload: Json;
}
export interface Request {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
  path: string;
  query: Record<string, string>;
  body: Json;
}
export interface Response { status: number; body: Json }
export interface Context {
  readonly site: Readonly<{ id: string; projectId: string; releaseId: string; sdkVersion: '1' }>;
  readonly invocation: Readonly<{
    id: string;
    source: 'internal' | 'callback';
    eventId: string | null;
    subscriptionId: string | null;
    /** Unix milliseconds. The host enforces a separate monotonic deadline. */
    deadlineAt: number;
    throwIfCancelled(): void;
  }>;
  readonly db: Database;
  readonly platform: SitePlatform;
  readonly log: Readonly<{
    info(message: string, data?: Json): void;
    warn(message: string, data?: Json): void;
    error(message: string, data?: Json): void;
  }>;
}
export type Handler = (request: Request, ctx: Context) => Response | Promise<Response>;



// Generated by platform-javascript-sdk. Do not edit.
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type AbortResponse = { "input": (RunInput | null); "run": Run };
export type AbortRun = { "reason"?: string | null; "runId": string };
export type Account = { "accountId": string; "name": string; "provider": string; "status": string };
export type AccountModels = { "accountId": string; "modelIds": Array<string>; "name": string; "provider": string };
export type ArtifactReference = { "artifact_id": string; "media_type": string; "sha256": string; "size_bytes": number };
export type Bash = { "command": string; "hostId": string; "timeoutMs"?: number | null; "workdir": string };
export type CompletionCallback = { "path": string; "payload"?: Json };
export type ContentPart = ({ "content": string; "metadata"?: { [key: string]: Json } | null; "type": "text" } | { "detail"?: (ImageDetail | null); "metadata"?: { [key: string]: Json } | null; "source": ImageSource; "type": "image" });
export type CreateRun = { "expectedRevision": number; "input": UserInput; "onComplete"?: (CompletionCallback | null); "sessionId": string };
export type CreateSandboxFromSnapshot = { "environmentId": string; "name"?: string | null; "timeoutSeconds"?: number | null };
export type CreateSession = { "accountId": string; "config": { [key: string]: Json }; "harnessId": string; "initialInput"?: (UserInput | null); "onComplete"?: (CompletionCallback | null); "title"?: string | null };
export type CursorPage_Account = { "items": Array<Account>; "next_cursor": string | null };
export type CursorPage_Environment = { "items": Array<Environment>; "next_cursor": string | null };
export type CursorPage_Harness = { "items": Array<Harness>; "next_cursor": string | null };
export type CursorPage_Run = { "items": Array<Run>; "next_cursor": string | null };
export type CursorPage_Session = { "items": Array<Session>; "next_cursor": string | null };
export type Environment = { "created_at": string; "id": string; "machine_id": string | null; "name": string; "path": string; "project_id": string; "snapshot_id": string | null; "type": EnvironmentType; "updated_at": string; "workspace_root": string };
export type EnvironmentCardinality = "single" | "multiple";
export type EnvironmentInput = { "cardinality": EnvironmentCardinality; "config_pointer": string; "required": boolean };
export type EnvironmentType = "machine" | "sandbox";
export type ErrorInfo = { "code": string; "message": string };
export type Execution = { "cancellationConfirmed": boolean; "cancellationRequested": boolean; "createdAt": string; "error": (ErrorInfo | null); "exitCode": number | null; "finishedAt": string | null; "hostId": string; "id": string; "outputBytes": number; "status": ExecutionStatus; "truncated": boolean };
export type ExecutionId = { "executionId": string };
export type ExecutionOutput = { "complete": boolean; "executionId": string; "nextCursor": string | null; "output": string; "outputBytes": number; "truncated": boolean };
export type ExecutionOutputOptions = { "cursor"?: string | null; "limitBytes"?: number | null };
export type ExecutionStatus = "pending" | "running" | "completed" | "failed" | "cancelled" | "lost";
export type ExecutionWorkspace = { "environment_id": string | null; "host_id": string; "path": string; "sandbox_id"?: string | null; "workspace_root": string };
export type Harness = { "config_schema": { [key: string]: Json } | null; "created_at": string; "default_config": { [key: string]: Json }; "description": string | null; "enabled": boolean; "harness_contract": HarnessContract; "id": string; "name": string; "project_policy": HarnessProjectPolicy; "supported_models": { [key: string]: Array<string> }; "updated_at": string };
export type HarnessContract = { "environment_inputs": Array<EnvironmentInput>; "outputs": { [key: string]: OutputDeclaration } };
export type HarnessProjectPolicy = "required" | "opt_in";
export type ImageDetail = "auto" | "low" | "high" | "original";
export type ImageSource = ({ "data": string; "mime_type": string; "type": "base64" } | { "type": "url"; "url": string });
export type InputState = "pending" | "handled" | "rejected";
export type MessageOptions = { "afterRevision"?: number | null; "limit"?: number | null; "runId"?: string | null };
export type MessagePage = { "items": Array<SessionMessage>; "next_after_revision": number | null };
export type MessageResponse = { "input": RunInput; "run": Run };
export type MutationOptions = { "idempotencyKey": string };
export type OutputDeclaration = { "description": string | null; "kind": OutputKind; "value_schema": { [key: string]: Json } | null };
export type OutputKind = "execution_workspace" | "json" | "artifact";
export type OutputOptions = { "afterSequence"?: number | null; "limit"?: number | null };
export type OutputValue = ({ "kind": "execution_workspace"; "value": ExecutionWorkspace } | { "kind": "json"; "value": Json } | { "kind": "artifact"; "value": ArtifactReference });
export type PageOptions = { "cursor"?: string | null; "limit"?: number | null };
export type RegisteredCallback = { "subscriptionId": string };
export type Run = { "abort_requested_at": string | null; "available_at": string | null; "config": { [key: string]: Json }; "created_at": string; "error": { [key: string]: Json } | null; "final_message_id": string | null; "finished_at": string | null; "id": string; "last_event_sequence": number; "parent_run_id": string | null; "project_id": string; "session_id": string; "started_at": string | null; "status": RunStatus; "version": number };
export type RunCreated = { "callback": (RegisteredCallback | null); "input": RunInput; "run": Run };
export type RunInput = { "created_at": string; "handled_at": string | null; "handling": { [key: string]: Json } | null; "id": string; "kind": string; "payload": { [key: string]: Json }; "project_id": string; "run_id": string; "sequence": number; "source_run_id": string | null; "status": InputState };
export type RunOutput = { "created_at": string; "name": string; "output": OutputValue; "project_id": string; "run_id": string; "sequence": number; "session_id": string };
export type RunOutputsPage = { "items": Array<RunOutput>; "next_after_sequence": number | null };
export type RunStatus = "ready" | "running" | "waiting" | "completed" | "failed" | "aborted";
export type Sandbox = { "createdAt": string; "environmentId": string; "error": (ErrorInfo | null); "expiresAt": string | null; "id": string; "status": SandboxStatus; "terminationConfirmed": boolean; "terminationRequested": boolean; "workspace": (ExecutionWorkspace | null) };
export type SandboxId = { "sandboxId": string };
export type SandboxStatus = "provisioning" | "ready" | "failed" | "terminated" | "expired" | "unavailable" | "terminating";
export type Session = { "active_run": (Run | null); "archived_at": string | null; "config": { [key: string]: Json }; "created_at": string; "current_revision": number; "forked_at_revision": number | null; "forked_from_session_id": string | null; "harness_contract": HarnessContract; "harness_id": string; "id": string; "last_activity_at": string; "project_id": string; "title": string | null };
export type SessionCreated = { "callback": (RegisteredCallback | null); "input": (RunInput | null); "run": (Run | null); "session": Session };
export type SessionMessage = { "created_at": string; "message": Json; "message_id": string; "origin_run_id": string | null; "revision": number; "run_id": string | null };
export type StartOptions = { "accounts": Array<AccountModels>; "configSchema": { [key: string]: Json } | null; "configurableFields": Array<string> | null; "defaultConfig": { [key: string]: Json }; "environmentMode": string | null; "harnessContract": HarnessContract; "harnessId": string };
export type Statistics = { "assistantMessages": number; "cacheReadTokens": UsageMetric; "cacheWriteTokens": UsageMetric; "costUsd": UsageMetric; "inputTokens": UsageMetric; "outputTokens": UsageMetric; "runId": string | null; "runWallSeconds": number | null; "sessionId": string };
export type SteerRun = { "input": UserInput; "runId": string };
export type UsageMetric = { "contributingMessages": number; "total": number | null };
export type UserInput = ({ "content": Array<ContentPart>; "id": string; "role": "user"; "timestamp": number });
export type Uuid = string;

export interface Platform {
  readonly accounts: Readonly<{
    /** List available LLM accounts as credential-free metadata. */
    list(options?: PageOptions): Promise<CursorPage_Account>;
  }>;
  readonly environments: Readonly<{
    /** List this project's environment references without provisioning hosts. */
    list(options?: PageOptions): Promise<CursorPage_Environment>;
    /** Get one project environment reference. */
    get(environmentId: Uuid): Promise<Environment>;
  }>;
  readonly execution: Readonly<{
    /** Accept durable bash execution on an authorized host with absolute workdir. Returns immediately with a persistent handle. */
    bash(input: Bash, options: MutationOptions): Promise<Execution>;
    /** Read durable command status and cancellation confirmation. */
    get(executionId: Uuid): Promise<Execution>;
    /** Read bounded UTF-8 output pages; a live empty page retains a polling cursor. */
    output(executionId: Uuid, options?: ExecutionOutputOptions): Promise<ExecutionOutput>;
    /** Request cancellation; transport errors and acknowledgements alone do not confirm termination. */
    cancel(input: ExecutionId, options: MutationOptions): Promise<Execution>;
  }>;
  readonly harnesses: Readonly<{
    /** List the project's enabled harnesses and configuration declarations. */
    list(options?: PageOptions): Promise<CursorPage_Harness>;
    /** Read a registered harness and its declared inputs and outputs. */
    get(harnessId: string): Promise<Harness>;
    /** Discover supported accounts/models and permitted harness configuration fields. */
    startOptions(harnessId: string): Promise<StartOptions>;
  }>;
  readonly runs: Readonly<{
    /** Create a run with canonical user input and an expected session revision. onComplete requires a site backend. */
    create(input: CreateRun, options: MutationOptions): Promise<RunCreated>;
    /** List a session's runs in cursor order. */
    list(sessionId: Uuid, options?: PageOptions): Promise<CursorPage_Run>;
    /** Inspect one exact run, including terminal status. */
    get(runId: Uuid): Promise<Run>;
    /** Append canonical user input to the selected live run; acceptance is not model consumption. */
    steer(input: SteerRun, options: MutationOptions): Promise<MessageResponse>;
    /** Request cooperative abort of one exact run. */
    abort(input: AbortRun, options: MutationOptions): Promise<AbortResponse>;
    /** Read recorded usage and wall time for one run. */
    stats(runId: Uuid): Promise<Statistics>;
    /** Read named immutable outputs. References do not grant resource access. */
    outputs(runId: Uuid, options?: OutputOptions): Promise<RunOutputsPage>;
  }>;
  readonly sandboxes: Readonly<{
    /** Accept durable sandbox provisioning from a project snapshot. Poll get until ready; never replace an evaluated workspace for verification. */
    createFromSnapshot(input: CreateSandboxFromSnapshot, options: MutationOptions): Promise<Sandbox>;
    /** Inspect sandbox readiness, expiry and confirmed termination. */
    get(sandboxId: Uuid): Promise<Sandbox>;
    /** Request sandbox termination; poll terminationConfirmed before assuming deletion. */
    terminate(input: SandboxId, options: MutationOptions): Promise<Sandbox>;
  }>;
  readonly sessions: Readonly<{
    /** Create a session with immutable configuration; optional initialInput creates its first run atomically. onComplete requires a site backend. */
    create(input: CreateSession, options: MutationOptions): Promise<SessionCreated>;
    /** Page through project sessions. */
    list(options?: PageOptions): Promise<CursorPage_Session>;
    /** Get session metadata and its current active run. */
    get(sessionId: Uuid): Promise<Session>;
    /** Page through explicit message history, optionally filtered by run. */
    messages(sessionId: Uuid, options?: MessageOptions): Promise<MessagePage>;
    /** Read recorded usage and wall time; absent metrics remain null. */
    stats(sessionId: Uuid): Promise<Statistics>;
  }>;
}

/** Agent cells may omit keys; the trusted adapter assigns and journals them. */
export interface AgentPlatform extends Omit<Platform, 'execution' | 'runs' | 'sandboxes' | 'sessions'> {
  readonly execution: Omit<Platform['execution'], 'bash' | 'cancel'> & Readonly<{
    bash(input: Bash, options?: MutationOptions): Promise<Execution>;
    cancel(input: ExecutionId, options?: MutationOptions): Promise<Execution>;
  }>;
  readonly runs: Omit<Platform['runs'], 'create' | 'steer' | 'abort'> & Readonly<{
    create(input: CreateRun, options?: MutationOptions): Promise<RunCreated>;
    steer(input: SteerRun, options?: MutationOptions): Promise<MessageResponse>;
    abort(input: AbortRun, options?: MutationOptions): Promise<AbortResponse>;
  }>;
  readonly sandboxes: Omit<Platform['sandboxes'], 'createFromSnapshot' | 'terminate'> & Readonly<{
    createFromSnapshot(input: CreateSandboxFromSnapshot, options?: MutationOptions): Promise<Sandbox>;
    terminate(input: SandboxId, options?: MutationOptions): Promise<Sandbox>;
  }>;
  readonly sessions: Omit<Platform['sessions'], 'create'> & Readonly<{
    create(input: CreateSession, options?: MutationOptions): Promise<SessionCreated>;
  }>;
}

/** Legacy backend aliases retained during migration. */
export type PlatformRecord = { [key: string]: Json };
export interface Page { items: PlatformRecord[]; next_cursor: string | null }
export type UserMessage = UserInput;
export interface StartSession {
  harnessId: string;
  environmentId?: string;
  prompt: string;
  title?: string;
  model: { provider: string; id: string };
  accountId: string;
  onComplete?: CompletionCallback;
  options?: { reasoningLevel?: string; webSearchEnabled?: boolean };
}
export interface AcceptedSession {
  sessionId: string;
  runId: string;
  session: PlatformRecord;
  run: PlatformRecord;
  input: PlatformRecord;
  callback?: { subscriptionId: string };
}

export interface SitePlatform extends Omit<Platform, 'sessions'> {
  readonly sessions: Platform['sessions'] & Readonly<{
    startOptions(harnessId: string): Promise<{
      harnessId: string; environmentRequired: boolean;
      accounts: { accountId: string; name: string; provider: string; modelIds: string[] }[];
      reasoningLevels: string[] | null; defaultReasoning: string | null;
      webSearchSupported: boolean; defaultWebSearch: boolean | null;
    }>;
    start(input: StartSession, options: MutationOptions): Promise<AcceptedSession>;
    metrics(sessionId: string, options?: { runId?: string }): Promise<PlatformRecord>;
    send(sessionId: string, input: { prompt: string; expectedRevision: number; expectedRunId: string | null; onComplete?: CompletionCallback }, options: MutationOptions): Promise<AcceptedSession>;
    stop(sessionId: string, options: MutationOptions & { expectedRunId: string; reason?: string }): Promise<AcceptedSession>;
  }>;
  readonly callbacks: Readonly<{
    list(options?: { limit?: number; after?: string }): Promise<{ items: PlatformRecord[]; next_after: string | null }>;
    get(callbackId: string): Promise<PlatformRecord>;
  }>;
}
